global:
  sitecore:
    appcd:
      host: ""
    kioskcd:
      host: ""
    app:
      host: ""
    kiosk:
      host: ""

sitecore-xp0:
  cm:
    cmp:
      contenthub: ""
      servicebusentitypathin: ""
      servicebussubscription: ""
      servicebusentitypathout: ""
    sfmc: ""

    env:
      - name: SITECORE_APPSETTINGS_ROLE__DEFINE
        value: "Standalone"
      - name: SITECORE_APPSETTINGS_SXAXM__DEFINE
        value: "sxaconnect"
      - name: SITECORE_APPSETTINGS_ENV__DEFINE
        value: "Production"
      - name: SITECORE_APPSETTINGS_UNICORN__DEFINE
        value: "Disabled"
      - name: SITECORE_APPSETTINGS_PUBLISHINGSERVICE__DEFINE
        value: "Enabled"
      - name: SITECORE_APPSETTINGS_INTEGRATIONS__DEFINE
        value: "None"
      - name: SITECORE_APPSETTINGS_CONTENTHUB__DEFINE
        value: "Enabled"
      - name: SITECORE_CONNECTIONSTRINGS_CMP.ContentHub
        value: |-
          "{{ .Values.cmp.contenthub }}"
      - name: SITECORE_CONNECTIONSTRINGS_CMP.ServiceBusEntityPathIn
        value: |-
          "{{ .Values.cmp.servicebusentitypathin }}"
      - name: SITECORE_CONNECTIONSTRINGS_CMP.ServiceBusSubscription
        value: |-
          "{{ .Values.cmp.servicebussubscription }}"
      - name: SITECORE_CONNECTIONSTRINGS_CMP.ServiceBusEntityPathOut
        value: |-
          "{{ .Values.cmp.servicebusentitypathout }}"
      - name: SITECORE_CONNECTIONSTRINGS_SFMC
        value: |-
          "{{ .Values.sfmc}}"
      - name: PROXY_API_HOST
        value: |-
          "https://{{ .Values.global.sitecore.cm.host }}"
  mssql:
    user:
      password: ""

    admin:
      username: ""
      password: ""
      disable:
        default: 'FALSE'
    dam:
      url: ""
    exm:
      baseUrl: ""
      kioskCdBaseUrl: ""
      appBaseUrl: ""
    boot:
      overrideScripts: "Demo-Boot-Platform-Linux.ps1;Demo-Boot-Omni-Linux.ps1"

    env:
      - name: USER_PASSWORD
        value: |-
          "{{ .Values.user.password }}"
      - name: ADMIN_USER_NAME
        value: |-
          "{{ .Values.admin.username }}"
      - name: DISABLE_DEFAULT_ADMIN
        value: |-
          "{{ .Values.admin.disable.default }}"
      - name: DAM_URL
        value: |-
          "{{ .Values.dam.url }}"
      - name: EXM_BASE_URL
        value: |-
          "{{ .Values.exm.baseUrl }}"
      - name: EXM_KIOSK_CD_BASE_URL
        value: |-
          "{{ .Values.exm.kioskCdBaseUrl }}"
      - name: EXM_APP_BASE_URL
        value: |-
          "{{ .Values.exm.appBaseUrl }}"
      - name: BOOT_OVERRIDE_SCRIPTS
        value: |-
          "{{ .Values.boot.overrideScripts }}"

  xdbautomationworker:
    env:
      - name: REACT_APP_PUBLIC_HOST_NAME
        value: |-
          "//{{ .Values.global.sitecore.app.host }}"

app:
  env:
    - name: SITECORE_API_HOST
      value: |-
        "https://{{ .Values.global.sitecore.appcd.host }}"
    - name: PROXY_API_HOST
      value: |-
        "https://{{ .Values.global.sitecore.app.host }}"

kiosk:
  env:
    - name: SITECORE_API_HOST
      value: |-
        "https://{{ .Values.global.sitecore.kioskcd.host }}"
    - name: PROXY_API_HOST
      value: |-
        "https://{{ .Values.global.sitecore.kiosk.host }}"
