# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '$(ServiceConnection)'
  imageRepository: 'Sitecore-Hostswriter'
  containerRegistry: '$(ContainerRegistry)'
  dockerfilePath: '$(Build.SourcesDirectory)/docker/tooling/sitecore-windows-hosts-writer/Dockerfile'
  tag: '$(Build.BuildId)-nanoserver-1809'

  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build container image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'
        arguments: '--build-arg BASE_IMAGE=$(BASE_IMAGE) --build-arg BASE_RUNTIME_IMAGE=$(BASE_RUNTIME_IMAGE)'
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)







