steps:
- task: gitversion/setup@0
  displayName: 'Install GitVersion'
  inputs:
    versionSpec: '5.3.3'
- task: gitversion/execute@0
  displayName: 'Execute GitVersion'
  inputs:
    runtime: 'core'
    useConfigFile: true
    configFilePath: 'docker/GitVersion.yml'
    additionalArguments: '/updateassemblyinfo'
- task: PowerShell@2
  displayName: 'Set correct image tag'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=tag]$(GitVersion.MajorMinorPatch)"'
  condition: eq(variables['GitVersion.PreReleaseLabel'], '')
- task: PowerShell@2
  displayName: 'Tag the PR without the version number'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=tag]$(GitVersion.PreReleaseLabel)"'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
- task: PowerShell@2
  displayName: 'Set additional image tag for PR'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=additionalImageTags]$(GitVersion.PreReleaseLabel)"'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
