# Default values for sitecore-demo-omni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

sql:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-sql:latest-linux
  volumeClaim:
    storageClassName: managed-premium
    storageSize: 5Gi
    accessModes:
      - ReadWriteOnce

solr:
  image:
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-solr:latest-linux
  volumeClaim:
    storageClassName: managed-premium
    storageSize: 1Gi
    accessModes:
      - ReadWriteOnce
cm:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-cm:latest
  adminPassword: abc
  unicornSharedSecret: abc

cd:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-cd:latest

ps:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-ps:latest

xconnect:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-xconnect:latest

indexworker:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-indexworker:latest

app:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-app:latest-linux

kiosk:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-kiosk:latest-linux

automationengine:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-automationengine:latest

redis:

initcontainer:
  image: 
    tag: sitecoredemocontainers.azurecr.io/lighthouse-jss-init:latest-linux

smtp:
  image:
    tag: maildev/maildev

global:
  licenseFileSecretName: license.xml
  sqlSaPassword: 2k_45454^sss!
  telerikEncryptionKey: qspJhcSmT5VQSfbZadFfzhCK6Ud7uRoS42Qcm8UofvVLiXciUBcUeZELsTo8KD9o6KderQr9Z8uZ9CHisFJNRz46WTZ5qCRufRFt

#####################################################################

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
