apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr
  name: solr
spec:
  ports:
  - name: "tcp"
    protocol: TCP
    port: 8983
    targetPort: 8983
  selector:
    app: solr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - image: "sitecoredemocontainers.azurecr.io/sitecoredemo-solr:{{ $.Chart.AppVersion }}"
        name: solr
        ports:
        - containerPort: 8983
        resources: {}
      restartPolicy: Always
status: {}
