apiVersion: v1
kind: Service
metadata:
  labels:
    app: xconnect
  name: xconnect
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app: xconnect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xconnect
  name: xconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xconnect
  template:
    metadata:
      labels:
        app: xconnect
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
        - command:
            - powershell.exe
            - -NoLogo
            - -NoProfile
            - -File
            - C:\tools\entrypoints\iis\development.ps1
          env:
            - name: Database_Username
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: sitecore-databaseusername.txt
            - name: Database_Password
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: sitecore-databasepassword.txt        
            - name: SITECORE_LICENSE
              valueFrom:
                secretKeyRef:
                  name: sitecore-license
                  key: sitecore-license.txt
            - name: SITECORE_SITECORE__XCONNECT__COLLECTIONSEARCH__SERVICES__SOLR.SOLRREADERSETTINGS__OPTIONS__REQUIREHTTPS
              value: 'false'    
            - name: SITECORE_SITECORE__XCONNECT__SEARCHINDEXER__SERVICES__SOLR.SOLRWRITERSETTINGS__OPTIONS__REQUIREHTTPS
              value: 'false'
            - name: SITECORE_CONNECTIONSTRINGS_MESSAGING
              value: Data Source=sql;Database=Sitecore.Messaging;User ID=$(Database_Username);Password=$(Database_Password)
            - name: SITECORE_CONNECTIONSTRINGS_PROCESSING.ENGINE.STORAGE
              value: Data Source=sql;Database=Sitecore.ProcessingEngineStorage;User ID=$(Database_Username);Password=$(Database_Password)
            - name: SITECORE_CONNECTIONSTRINGS_REPORTING
              value: Data Source=sql;Database=Sitecore.Reporting;User ID=$(Database_Username);Password=$(Database_Password)     
            - name: SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION
              value: Data Source=sql;Database=Sitecore.MarketingAutomation;User ID=$(Database_Username);Password=$(Database_Password)
            - name: SITECORE_CONNECTIONSTRINGS_XDB.PROCESSING.POOLS
              value: Data Source=sql;Database=Sitecore.Processing.Pools;User ID=$(Database_Username);Password=$(Database_Password)
            - name: SITECORE_CONNECTIONSTRINGS_XDB.REFERENCEDATA
              value: Data Source=sql;Database=Sitecore.ReferenceData;User ID=$(Database_Username);Password=$(Database_Password)
            - name: SITECORE_CONNECTIONSTRINGS_COLLECTION
              value: Data Source=sql;Database=Sitecore.Xdb.Collection.ShardMapManager;User ID=$(Database_Username);Password=$(Database_Password)
            - name: SITECORE_CONNECTIONSTRINGS_SOLRCORE
              value: http://solr:8983/solr/sitecore_xdb
          image: "sitecoredemocontainers.azurecr.io/sitecoredemo-xconnect:{{ $.Chart.AppVersion }}"
          name: xconnect
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
