apiVersion: v1
kind: Service
metadata:
  labels:
    app: xconnect-automationengine
  name: xconnect-automationengine
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app: xconnect-automationengine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xconnect-automationengine
  name: xconnect-automationengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xconnect-automationengine
  template:
    metadata:
      labels:
        app: xconnect-automationengine
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
        - command:
            - powershell.exe
            - -NoLogo
            - -NoProfile
            - -File
            - C:\tools\entrypoints\worker\Development.ps1
          image: "sitecoredemocontainers.azurecr.io/sitecoredemo-automationengine:{{ $.Chart.AppVersion }}"
          env:
            - name: Database_Username
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: sitecore-databaseusername.txt
            - name: Database_Password
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: sitecore-databasepassword.txt
            - name: SITECORE_LICENSE
              valueFrom:
                secretKeyRef:
                  name: sitecore-license
                  key: sitecore-license.txt
            - name: SITECORE_CONNECTIONSTRINGS_XCONNECT.COLLECTION
              value: http://xconnect
            - name: SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION
              value: Data Source=sql;Database=Sitecore.MarketingAutomation;User ID=$(Database_Username);Password=$(Database_Password)
            - name: SITECORE_CONNECTIONSTRINGS_XDB.REFERENCEDATA
              value: Data Source=sql;Database=Sitecore.ReferenceData;User ID=$(Database_Username);Password=$(Database_Password)
            - name: SITECORE_CONNECTIONSTRINGS_MESSAGING
              value: Data Source=sql;Database=Sitecore.Messaging;User ID=$(Database_Username);Password=$(Database_Password)
          name: xconnect-automationengine
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
